// Persistence layer for in-app notifications using SQLite.
// Notifications are generated by key events (campaigns, SoD, evidence, etc.)
// and displayed in the topbar bell icon dropdown.

const crypto = require('crypto');
const { getDb } = require('./db');

const DEFAULT_LIMIT = 50;

function newId() {
  return 'notif_' + crypto.randomUUID().slice(0, 12);
}

const VALID_TYPES = ['campaign', 'sod', 'evidence', 'submission', 'system', 'data'];

function normalize(notif) {
  const n = notif || {};
  return {
    id: n.id || newId(),
    tenant_id: n.tenant_id || 'default',
    type: VALID_TYPES.includes(n.type) ? n.type : 'system',
    title: String(n.title || '').trim(),
    body: String(n.body || '').trim(),
    link: String(n.link || '').trim(),
    icon: String(n.icon || '').trim() || iconForType(n.type),
    read: n.read ? 1 : 0,
    email: String(n.email || '').trim(),
    created_at: n.created_at || new Date().toISOString(),
  };
}

function iconForType(type) {
  const icons = {
    campaign: '📋',
    sod: '⚠️',
    evidence: '📦',
    submission: '✅',
    system: 'ℹ️',
    data: '📊',
  };
  return icons[type] || '🔔';
}

class SqliteNotificationStore {
  constructor() {
    this.db = getDb();
  }

  async create(notif) {
    const n = normalize(notif);
    this.db.prepare(`
      INSERT INTO notifications (id, tenant_id, type, title, body, link, icon, read, email, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(n.id, n.tenant_id, n.type, n.title, n.body, n.link, n.icon, n.read, n.email, n.created_at);
    return n;
  }

  async readAll(filters = {}) {
    let sql = 'SELECT * FROM notifications WHERE 1=1';
    const params = [];
    const tenantId = filters.tenant_id || 'default';
    sql += ' AND tenant_id = ?';
    params.push(tenantId);

    if (filters.type) { sql += ' AND type = ?'; params.push(filters.type); }
    if (filters.email) { sql += ' AND email = ?'; params.push(filters.email); }
    if (filters.read !== undefined) {
      sql += ' AND read = ?';
      params.push(filters.read ? 1 : 0);
    }

    sql += ' ORDER BY created_at DESC';
    const limit = Number(filters.limit) > 0 ? Number(filters.limit) : DEFAULT_LIMIT;
    sql += ' LIMIT ?';
    params.push(limit);

    const rows = this.db.prepare(sql).all(...params);
    return rows.map(r => ({
      id: r.id,
      tenant_id: r.tenant_id,
      type: r.type,
      title: r.title,
      body: r.body,
      link: r.link,
      icon: r.icon,
      read: !!r.read,
      email: r.email,
      created_at: r.created_at,
    }));
  }

  async getUnreadCount(tenant_id = 'default') {
    const row = this.db.prepare(
      'SELECT COUNT(*) as cnt FROM notifications WHERE tenant_id = ? AND read = 0'
    ).get(tenant_id);
    return row ? row.cnt : 0;
  }

  async markRead(id) {
    this.db.prepare('UPDATE notifications SET read = 1 WHERE id = ?').run(id);
  }

  async markAllRead(tenant_id = 'default') {
    this.db.prepare('UPDATE notifications SET read = 1 WHERE tenant_id = ? AND read = 0').run(tenant_id);
  }

  async deleteOld(days = 30) {
    const cutoff = new Date(Date.now() - days * 86400000).toISOString();
    this.db.prepare('DELETE FROM notifications WHERE created_at < ?').run(cutoff);
  }
}

function createNotificationStore() {
  return new SqliteNotificationStore();
}

module.exports = { createNotificationStore, SqliteNotificationStore };
